name: noter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: github.com/magefile/mage
        uses: actions/setup-go@v4
        with:
           go-version-file: 'go.mod'

      - name: Mage
        run: |
          cd mage
          go run bootstrap.go install
          echo $PATH
          echo ${{env.GOPATH}}

      - name: Build
        run: mage build

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: noter
          path: noter