name: noter

on:
  workflow_dispatch:
  push:
    paths:
      - 'VERSION'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
           go-version: '1.21.0'

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            export V=$(cat VERSION)
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/"$(cat VERSION)"',
              sha: context.sha
            })

      - name: Build Linux
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: linux

      - name: Build MacOS
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: mac
          
      - name: Build Windows
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: windows

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./bin/linux/noter
            ./bin/mac/noter
            ./bin/windows/noter