name: noter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: magefile/mage
          fetch-depth: 0
          path: mage
      - uses: actions/setup-go@v4
        with:
           go-version-file: 'go.mod'

      - name: Mage
        run: |
          ls -al
          cd mage
          go run bootstrap.go install
          echo $PATH
          echo ${{env.GOPATH}}

      - name: Build
        run: /home/runner/go/bin/mage build

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: noter
          path: noter