name: noter

on:
  workflow_dispatch:
  push:
    paths:
      - 'VERSION'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
           go-version: '1.21.0'
      - name: Get version
        id: vars
        run: echo ::set-output name=version::$(cat VERSION)
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.vars.outputs.version }}",
              sha: context.sha
            })
          
      - name: Build Linux
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: linux

      - name: Build MacOS
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: mac
          
      - name: Build Windows
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: windows
        
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: noter-linux
          path: ./bin/linux/noter

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: noter-mac
          path: ./bin/macos/noter

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: noter-windows
          path: ./bin/windows/noter