name: noter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
           go-version: '1.21.0'

      - name: Build Linux
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: buildlinux

      - name: Build MacOS
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: buildmacos

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: noter
          path: ./bin/linux/noter

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: noter-mac
          path: ./bin/macos/noter