name: noter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Mage
        run: |
          git clone git@github.com:magefile/mage
          cd mage
          go run bootstrap.go install

      - name: Build
        run: mage build

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: noter
          path: noter