name: noter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'

      - name: Mage
        run: |
          echo $PATH
          echo $GOPATH
          echo $GOROOT
          go get -d github.com/magefile/mage
          go run $GOPATH/src/github.com/magefile/mage/bootstrap.go install

      - name: Build
        run: mage build

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: noter
          path: noter